### ISSUE TITLE
Sputnik.ci hasn't started a build

### ISSUE THREAD

**Issue by arkadius** [TouK/sputnik-ci#1]
Here is my PR: https://github.com/arkadius/reliable-http-client/pull/7
I've configured circle.yml just like the doc said and it was done before I've created a PR.

Any help?

**Comment by pjagielski** [comment]
Thanks for submission - it's a bug. We check CIRCLE_PR_NUMBER which is set only on builds from forks. Working on the fix.

**Comment by rafalnowak** [comment]
Problem with CircleCI environment variables was solved in https://github.com/TouK/sputnik-ci/pull/2
