### ISSUE TITLE
Configure FindBugs to ignore some warnings

### ISSUE THREAD

**Issue by akiezun** [TouK/sputnik-ci#11]
Can I configure FindBugs to ignore some things eg the default encoding issues?
https://github.com/broadinstitute/gatk/pull/1822#partial-pull-merging 

I want to ignore all those
"[FindBugs] WARNING: Dm: Found reliance on default encoding in org.broadinstitute.hellbender.utils.variant.GATKVariantContextUtilsUnitTest.testFindNumberOfRepetitionsFullArray(): String.getBytes()"

**Comment by pjagielski** [comment]
Hi,
In recent version we added "I have my own config" which can be enabled on FindBugs.

![own_configs](https://cloud.githubusercontent.com/assets/513361/15352699/b8d9075e-1ce5-11e6-8b7c-59a283d9c364.png)

The file should be named `findbugs.xml` in the root of project. We are planning to let you choose a file from your repository.

You can add a rule to filter out this particular rule with something like this (haven't tested):

```
<Match>
  <Not>
      <Bug code="Dm" />
   </Not>
</Match>
```

**Comment by pjagielski** [comment]
@akiezun, you can now select file with findbugs configuration from your repository files:

![image](https://cloud.githubusercontent.com/assets/513361/15652241/1554d15e-2685-11e6-80ec-16db6694872e.png)
