### ISSUE TITLE
Incorrect github PR link

### ISSUE THREAD

**Issue by coutoPL** [TouK/sputnik-ci#12]
Page: https://sputnik.ci/app#/builds/TouK/influxdb-reporter

When I click "Pull request on Github" button I'm redirected to 
https://github.com/TouK/influxdb-reporter/pull/ and Github returns 404.

Should be:
https://github.com/TouK/influxdb-reporter/pulls

**Comment by rafalnowak** [comment]
Seems to be working now. These button links to GitHub pull request associated with chosen build. Please check if it is working for you.
