### ISSUE TITLE
TravisCI not working

### ISSUE THREAD

**Issue by MTRNord** [TouK/sputnik-ci#14]
It fails with
```
[INFO] 2017-06-04 13:59:25,519 Detected CI TRAVIS
[DEBUG] 2017-06-04 13:59:25,520 Problem while reading env variable: sputnik_api_key
[ERROR] 2017-06-04 13:59:25,520 Stop processing as pull request has not been initiated
```

**Comment by ghost** [comment]
Can confirm: https://travis-ci.org/mueller-ma-bot/openhab.android/jobs/362179203#L1596
I'm using build stages that are still in beta. Can this be the reason?

**Comment by pjagielski** [comment]
@mueller-ma-bot Maybe, Sputnik tries to read TRAVIS_PULL_REQUEST environment variable, is this present in your build?

**Comment by mueller-ma** [comment]
Yes, but it is set to false: https://travis-ci.org/mueller-ma-bot/openhab.android/jobs/363034287#L1582

**Comment by mueller-ma** [comment]
It was set to `false`, because it was a PR from one branch of this repo in master. I made a new PR with a branch from my repo to my bot's repo and now the variable is set to `8`.

**Comment by pjagielski** [comment]
@mueller-ma @MTRNord Can I close this for now?

**Comment by MTRNord** [comment]
@pjagielski From my point of view yes. (I didnt even remember this Issue until the comment)

**Comment by mueller-ma** [comment]
This is fixed for me as well.
