### ISSUE TITLE
Sputnik fails to post on Pull Requests, missing `sputnik_api_key` (public repo)

### ISSUE THREAD

**Issue by mcomella** [TouK/sputnik-ci#15]
According to the logs, it runs, finds violations, but appears to fail while posting the results to our repository due to a missing `sputnik_api_key`:

```
[DEBUG] 2018-03-21 16:42:42,688 Problem while reading env variable: sputnik_api_key
...
16:42:50.410 [main] INFO  p.t.s.connector.saas.SaasConnector - Sending violations: [{"file":".travis.yml","violations":[]},{"file":"README.md","violations":[]},{"file":"app/src/main/java/org/mozilla/focus/utils/DrawableUtils.java","violations":[{"line":21,"message":"[Checkstyle] ERROR: \u0027+\u0027 is not preceded with whitespace."},{"line":21,"message":"[Checkstyle] ERROR: \u0027+\u0027 is not followed by whitespace."}]}]
16:42:50.411 [main] INFO  p.t.s.connector.http.HttpConnector - Request  2: POST to https://sputnik.ci:443/api/github/mozilla-mobile/firefox-tv/pulls/704/violations?build_id=356442105
16:42:52.498 [main] INFO  p.t.s.connector.http.HttpConnector - Response 2: HTTP/1.1 500 Server Error
Exception in thread "main" pl.touk.sputnik.connector.saas.SaasException: Error when listing files, check your api key
	at pl.touk.sputnik.connector.saas.SaasFacade.publish(SaasFacade.java:65)
	at pl.touk.sputnik.engine.Engine.run(Engine.java:47)
	at pl.touk.sputnik.Main.main(Main.java:36)
Caused by: pl.touk.sputnik.connector.http.HttpException: Response status [500]
	at pl.touk.sputnik.connector.http.HttpConnector.consumeAndLogEntity(HttpConnector.java:56)
	at pl.touk.sputnik.connector.saas.SaasConnector.sendReview(SaasConnector.java:55)
	at pl.touk.sputnik.connector.saas.SaasFacade.publish(SaasFacade.java:63)
	... 2 more
```

We're using travis on a public repository.

Tracking for us in https://github.com/mozilla-mobile/firefox-tv/issues/483. This also looks like #14, but that appears to be a more comprehensive problem than the one I'm having.

**Comment by pjagielski** [comment]
Hi, Sputnik is having issues in creating a build status via GitHub API ,could you please check if you can see `sputnikci` user (https://github.com/sputnikci) in your project's Collaborators list?

**Comment by mcomella** [comment]
@pjagielski I do not see `sputnikci` in my project's Collaborators list.

Is this required for public repositories? I don't see anything about adding `sputnik` as a Collaborator in the [Getting Started documentation](https://github.com/TouK/sputnik-ci/wiki/Getting-started) and I noticed I can post comments on other public repositories PRs without being a collaborator.

By the way, thanks for getting back to me so quickly. :)

**Comment by pjagielski** [comment]
Yes, some Github API operations require additional permissions. All you have to do is login into https://sputnik.ci and enable your project. Sputnik user should be added to project then. 
Please let me know if it helped.

**Comment by mcomella** [comment]
> All you have to do is login into https://sputnik.ci and enable your project. Sputnik user should be added to project then.

Sputnik is enabled for my projects (which notably are for an organization I'm in, not my personal repos):

![screenshot-2018-3-23 sputnik](https://user-images.githubusercontent.com/759372/37852855-71513620-2ea1-11e8-8a65-ebc13d462472.png)

But the `sputnikci` user is not a collaborator. Should I give the user access manually? And if I do, what permissions (e.g. read/write) are required?

**Comment by pjagielski** [comment]
Ok, my fault, collaborator access is requested only for private repos.

Looks like we deployed a version with bug in authorization - I reverted it. It should work now - could you please re-run your Travis build and let me know if it helped?

**Comment by mcomella** [comment]
It worked! https://github.com/mozilla-mobile/firefox-tv/pull/704#pullrequestreview-107035172 (but, fwiw, Sputnik seems to have commented twice).

Thanks for resolving this so quickly!

**Comment by pjagielski** [comment]
Thanks for the test, I'm glad it worked.

Regarding the comments - they're a bit different: one is that '+' is 'preceded' and one that is 'followed' by whitespace ;)
