### ISSUE TITLE
Unable to create Checkstyle checker

### ISSUE THREAD

**Issue by mueller-ma** [TouK/sputnik-ci#16]
I have configured Sputnik CI and Stickler CI to use the same checkstyle.xml, but Sputnik fails to find the syntax errors. See https://github.com/mueller-ma-bot/openhab.android/pull/8 and the CI run https://travis-ci.org/mueller-ma-bot/openhab.android/jobs/363141522#L1618

**Comment by pjagielski** [comment]
Hi, we had old Sputnik version in script executed from Travis. I upgraded it, could you check it now?

**Comment by mueller-ma** [comment]
Hey @pjagielski,
thanks for fixing it, works now: https://github.com/mueller-ma-bot/openhab.android/pull/8/files/2473cc5b034c1e91f4e7de8896101768ea07d348#diff-07e4a6e281af02db331ff3f81d9f86d8
