### ISSUE TITLE
Violations are found but not reported

### ISSUE THREAD

**Issue by FlorianLautenschlager** [TouK/sputnik-ci#3]
Hi (again),

everything looks fine as the build log shows.
Sputnik discovered a few violations on the changed files.

```
15:02:11.159 [main] INFO  p.t.s.connector.saas.SaasConnector - Sending violations: [{"file":"README.adoc","violations":[]},{"file":"chronix-solr-cloud-storage/src/main/java/de/qaware/chronix/storage/solr/converter/Util.java","violations":[{"line":29,"message":"[Checkstyle] ERROR: Class Util should be declared as final."}]},{"file":"chronix-solr-cloud-storage/src/main/java/de/qaware/chronix/storage/solr/stream/TimeSeriesConverterCaller.java","violations":[]},{"file":"chronix-spark-ts-rdd/src/main/java/de/qaware/chronix/spark/api/java/ChronixRDD.java","violations":[{"line":115,"message":"[Checkstyle] ERROR: \u0027typecast\u0027 is not followed by whitespace."},{"line":121,"message":"[Checkstyle] ERROR: Comment matches to-do format \u0027TODO:\u0027."}]}]
15:02:11.161 [main] INFO  p.t.s.connector.http.HttpConnector - Request  2: POST to https://sputnik.ci/api/github/ChronixDB/chronix.spark/pulls/9/violations?build_id=122809501
15:02:11.615 [main] INFO  p.t.s.connector.http.HttpConnector - Response 2: HTTP/1.1 201 Created
15:02:11.616 [main] INFO  p.t.s.connector.http.HttpConnector - Entity 2: {"created":true}
```

But i could not find any reported violations on the [Pull Request](https://github.com/ChronixDB/chronix.spark/pull/9).
I thought sputnik-ci would comment the changed files?

Cheers,
Florian

**Comment by pjagielski** [comment]
What you see in build log is Sputnik analyzing whole files from your pull requests. Sputnik then sends this violations to sputnik.ci where is a logic of discovering if that violations concern lines modified in this pull request. In your case the lines reported by Sputnik are not part of changes in your pull request, so violations are not reported.

You can see sample project showing this flow here https://github.com/TouK/sputnik-test/pull/3

I hope it's more clear now.

**Comment by FlorianLautenschlager** [comment]
Gotcha.
