### ISSUE TITLE
Build doesn't start.

### ISSUE THREAD

**Issue by time2die** [TouK/sputnik-ci#5]
Good day ! I have very simple repo for testing sputnik.
https://github.com/time2die/Integration, i do all like you write in you docs , but it doesn't help me to start has information from sputnik.

**Comment by time2die** [comment]
log from travis

> The command "gradle check" exited with 0.
> after_success
> 0.12s$ python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
> [DEBUG] 2016-04-21 18:12:26,978 Problem while reading env variable: sputnik_api_key
> [ERROR] 2016-04-21 18:12:26,978 Stop processing as pull request has not been initiated

**Comment by pjagielski** [comment]
Hi, thanks for using Sputnik. As log says `pull request has not been initiated`. Sputnik works on pull requests; you can read more about it in [this FAQ entry](https://github.com/TouK/sputnik-ci/wiki/FAQ#how-does-review-process-look-from-further-perspective)

**Comment by time2die** [comment]
It work fine, thx for you project !
