### ISSUE TITLE
Checkstyle output needs to be escaped for Github comments

### ISSUE THREAD

**Issue by cketti** [TouK/sputnik-ci#6]
E.g. `*` is a special character in Markdown.

Currently
`[Checkstyle] INFO: Using the '.*' form of import should be avoided - java.util.*.`
will be displayed as
[Checkstyle] INFO: Using the '._' form of import should be avoided - java.util._.

This probably applies to the output of other tools as well.

**Comment by rafalnowak** [comment]
Fixed in the latest version.
