### ISSUE TITLE
As a repository owner I would like to provide link to custom Checkstyle file

### ISSUE THREAD

**Issue by tdziurko** [TouK/sputnik-ci#9]
For projects using custom checkstyle file Sputnik checks add many unnecessary noise. For now I've switched checkstyle checks off but it would be nice to have the ability to provide link to own, custom checkstyle file.

**Comment by pjagielski** [comment]
Yes, it's in progress. We'll let you know when it's finished,

**Comment by rafalnowak** [comment]
@tdziurko This feature is ready and is on production since few days. Please give it a try and configure Sputnik to use your own Checkstyle configs.
